name: compound
description: TrashApp

version: 2.0.4+30
  
environment:
  sdk: ">=2.6.0 <3.0.0"
    
dependency_overrides:
    intl: ^0.17.0-nullsafety.2
    flutter_datetime_picker:
      git:
        url: https://github.com/espresso3389/flutter_datetime_picker
    date_range_picker:
      git:
        url: https://github.com/ashokavarthanan/date_range_picker.git
        ref: patch-1
    textfield_tags:
      git:
        url: https://github.com/progress87/textfield_tags.git
        ref: v1.4.3-static-fix
dependencies:
  flutter:
    sdk: flutter
    
  timezone: ^0.6.1
  lat_lng_to_timezone: ^0.2.0
  sticky_and_expandable_list: 1.0.3
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.0.0
  http: ^0.12.0+2
  async: ^2.0.8
  get_it: ^3.0.0+1
  provider: ^4.0.5+1
  stacked: ^1.7.7
  logger: ^0.7.0+2
  equatable: ^1.0.1
  responsive_builder: ^0.1.4
  universal_html: ^1.1.0
  flutter_form_builder: ^4.2.0
  flutter_responsive: ^0.0.6
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^4.0.1+2
  mime_type: ^0.3.0 
  image_cropper: ^1.2.2
  camera: ^0.7.0+4
  file_picker: ^1.11.0+3
  file_picker_web: ^1.0.1+1
  table_calendar: ^3.0.0
  month_picker_dialog: ^0.3.1
  date_utils: ^0.1.0+3
  time_range_picker: 2.0.1
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.4.10
  percent_indicator: ^2.1.9+1
  csv: ^4.1.0
  path_provider: 1.6.5
  downloads_path_provider_28: ^0.1.2
  permission_handler: ^5.1.0+2
  device_info: 1.0.0
  firebase: ^7.3.0          #web impl
  cloud_firestore: ^0.13.7  #web&mobile impl
  cloud_functions: ^0.5.0
  firebase_auth: ^0.15.3    #mobile impl
  firebase_storage: ^3.1.1 
  firebase_analytics: ^5.0.16
  firebase_dynamic_links: ^0.5.0+11
  firebase_crashlytics: ^0.1.4+1
  image_picker: ^0.6.6+1 
  image_picker_web: ^1.0.9
  google_places_flutter: ^2.0.3
 
  flutter_native_image: ^0.0.4 
  cached_network_image: ^2.0.0-rc
  flutter_dialogflow: ^0.1.3
  fluttertoast: ^3.1.0
  photo_view: ^0.9.0
  connectivity: ^0.4.9
  purchases_flutter: ^1.1.1
  package_info: ^0.4.1
  sliver_fab: ^1.0.0
  sliver_fill_remaining_box_adapter: ^0.1.1
  transparent_image: ^1.0.0
  gallery_saver: ^2.0.2
  carousel_slider: ^2.3.1
  google_maps_flutter: ^1.2.0
  flutter_screenutil: ^4.0.2+8
  flutter_typeahead: ^1.9.1
  textfield_tags: ^1.4.3
  email_validator: ^1.0.6
  geolocator: ^6.2.1
  geocoding: ^1.0.5
  encrypt: ^4.1.0
  mask_text_input_formatter: ^1.2.1
  progressive_image: ^2.0.0
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/images/
      - assets/data/
      - assets/icons/
  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Myriad Pro
      fonts:
        - asset: assets/fonts/Myriad-Pro-Regular.ttf
          weight: 400
    - family: Avenir Next
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/AvenirNextLTPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/AvenirNextLTPro-It.ttf
          weight: 300
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
