name:  CollegeApp Build and Distribute Release (TODO)
on:
  pull_request:
    branches:
      - master
jobs:
          
   build:
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8   
      - uses: subosito/flutter-action@v1
        with:
         flutter-version: '1.17'
         channel: 'beta'
      - run: flutter analyze
      - run: flutter build apk
      - name: Upload APK DEBUG
        uses: actions/upload-artifact@v2
        with:
          name: college_app_debug_apk
          path: build/app/outputs/apk/debug/app-debug.apk
            
   distribute:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Download APK DEBUG
        uses: actions/download-artifact@v2
        with:
          name: college_app_debug_apk
      - name: upload APK DEBUG to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
            appId: ${{secrets.FIREBASE_APP_ID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            groups: the-team
            file: /home/runner/work/college-app/college-app/app-debug.apk